### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by razvanab** [leejet/stable-diffusion.cpp#604]
Cuda error

`.\sd.exe -m ".\SDXL.safetensors" --lora-model-dir ".\loras\SDXL" --clip-skip 2 --seed -1 --steps 25 --cfg-scale 7.5  -H 768 -W 768 --schedule exponential --sampling-method euler_a  -p "a woman in red in the park" --negative-prompt " messy drawing, amateur drawing, ugly face, bad face, bad teeth, (interlocked fingers, extra fingers, badly drawn hands and fingers, anatomically incorrect hands, bad anatomy), (blurry, depth of field) ,sketch, painting, simple background, white background" --vae ".\Vae\fp16_fix_sdxl_vae.safetensors"`

GPU: RTX 3050 8GB Vram
Cuda toolkit 12.4

PyTorch version: 2.6.0+cu124
CUDA toolkit version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

```
ggml_cuda_compute_forward: GET_ROWS failed
CUDA error: no kernel image is available for execution on the device
  current device: 0, in function ggml_cuda_compute_forward at D:\a\stable-diffusion.cpp\stable-diffusion.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:2174
  err
D:\a\stable-diffusion.cpp\stable-diffusion.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:70: CUDA error
```

**Comment by fszontagh** [comment]
If I'm right, this is a precompiled version of sd.exe.

The error you encountered:

**"_CUDA error: no kernel image is available for execution on the device_"**

This means your GPU's architecture is not supported. You need to compile it yourself or You can try to run the Linux version in WSL. 

The _"PyTorch version: 2.6.0+cu124"_ information is not relevant here, as there are no Python dependencies.

**Comment by razvanab** [comment]
I see. 
Thanks

**Comment by SkutteOleg** [comment]
Same issue. The precompiled version of sd.exe worked fine before.

**Comment by TheMcSebi** [comment]
Similar error here, using a 3090. Does that mean ada is not supported in the precompiled builds?
Just that in my case, IM2COL failed.

Some more output before the error
```
[INFO ] stable-diffusion.cpp:654  - total params memory size = 21676.60MB (VRAM 21676.60MB, RAM 0.00MB): text_encoders 9391.21MB(VRAM), diffusion_model 12125.39MB(VRAM), vae 160.00MB(VRAM), controlnet 0.00MB(VRAM), pmid 0.00MB(VRAM)
[INFO ] stable-diffusion.cpp:684  - running in Flux FLOW mode
[DEBUG] stable-diffusion.cpp:718  - finished loaded file
[DEBUG] stable-diffusion.cpp:2167 - generate_image 512x512
[INFO ] stable-diffusion.cpp:2300 - TXT2IMG
[INFO ] stable-diffusion.cpp:2308 - EDIT mode
[DEBUG] ggml_extend.hpp:1428 - vae compute buffer size: 848.50 MB(VRAM)
ggml_cuda_compute_forward: IM2COL failed
CUDA error: no kernel image is available for execution on the device
  current device: 0, in function ggml_cuda_compute_forward at D:\a\stable-diffusion.cpp\stable-diffusion.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:2522
  err
D:\a\stable-diffusion.cpp\stable-diffusion.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:87: CUDA error
```

**Comment by razvanab** [comment]
According to this: master-0e86d90

stable-diffusion.cpp should work on Nvidia 3xxx series RTX
but it still doesn't:

.\sd.exe --diffusion-model "D:\MODELS\Chroma\Chroma1-HD-Flash-Q8_0.gguf" --t5xxl "D:\MODELS\Clip\flan_t5_xxl_TE-only_Q6_K.gguf" --vae "D:\MODELS\Vae\Vae_FLUX.1-schnell.safetensors" --prompt "a woman face" --clip-on-cpu
[INFO ] ggml_extend.hpp:65   - ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
[INFO ] ggml_extend.hpp:65   - ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
[INFO ] ggml_extend.hpp:65   - ggml_cuda_init: found 1 CUDA devices:
[INFO ] ggml_extend.hpp:65   -   Device 0: NVIDIA GeForce RTX 3050, compute capability 8.6, VMM: yes
[INFO ] stable-diffusion.cpp:208  - loading diffusion model from 'D:\MODELS\Chroma\Chroma1-HD-Flash-Q8_0.gguf'
[INFO ] model.cpp:1035 - load D:\MODELS\Chroma\Chroma1-HD-Flash-Q8_0.gguf using gguf format
[INFO ] stable-diffusion.cpp:248  - loading t5xxl from 'D:\MODELS\Clip\flan_t5_xxl_TE-only_Q6_K.gguf'
[INFO ] model.cpp:1035 - load D:\MODELS\Clip\flan_t5_xxl_TE-only_Q6_K.gguf using gguf format
[INFO ] stable-diffusion.cpp:255  - loading vae from 'D:\MODELS\Vae\Vae_FLUX.1-schnell.safetensors'
[INFO ] model.cpp:1038 - load D:\MODELS\Vae\Vae_FLUX.1-schnell.safetensors using safetensors format
[INFO ] stable-diffusion.cpp:267  - Version: Flux
[INFO ] stable-diffusion.cpp:301  - Weight type:                 q8_0
[INFO ] stable-diffusion.cpp:302  - Conditioner weight type:     q6_K
[INFO ] stable-diffusion.cpp:303  - Diffusion model weight type: q8_0
[INFO ] stable-diffusion.cpp:304  - VAE weight type:             f32
[INFO ] stable-diffusion.cpp:341  - CLIP: Using CPU backend
[INFO ] flux.hpp:937  - Flux blocks: 19 double, 38 single
[INFO ] flux.hpp:939  - Using pruned modulation (Chroma)
  |==================================================| 1106/1106 - 59.03it/s
  |==================================================| 1106/1106 - 239.50it/s
  |==================================================| 1106/1106 - 2910.53it/s
[INFO ] model.cpp:2222 - loading tensors completed, taking 23.77s (process: 0.03s, read: 17.37s, memcpy: 0.00s, convert: 0.15s, copy_to_backend: 5.82s)
[INFO ] stable-diffusion.cpp:662  - total params memory size = 12856.43MB (VRAM 9130.21MB, RAM 3726.22MB): text_encoders 3726.22MB(RAM), diffusion_model 9035.64MB(VRAM), vae 94.57MB(VRAM), controlnet 0.00MB(VRAM), pmid 0.00MB(RAM)
[INFO ] stable-diffusion.cpp:692  - running in Flux FLOW mode
[INFO ] stable-diffusion.cpp:2315 - TXT2IMG
[INFO ] stable-diffusion.cpp:860  - attempting to apply 0 LoRAs
[INFO ] stable-diffusion.cpp:880  - apply_loras completed, taking 0.00s
[INFO ] stable-diffusion.cpp:1971 - get_learned_condition completed, taking 70640 ms
[INFO ] stable-diffusion.cpp:1994 - sampling using Euler A method
[INFO ] stable-diffusion.cpp:2043 - generating image: 1/1 - seed 42
[ERROR] ggml_extend.hpp:71   - CUDA error: no kernel image is available for execution on the device
[ERROR] ggml_extend.hpp:71   -   current device: 0, in function ggml_cuda_op_mul_mat at D:\a\stable-diffusion.cpp\stable-diffusion.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:1705
[ERROR] ggml_extend.hpp:71   -   cudaGetLastError()
D:\a\stable-diffusion.cpp\stable-diffusion.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:87: CUDA error

**Comment by fszontagh** [comment]
> According to this: master-0e86d90
> 
> stable-diffusion.cpp should work on Nvidia 3xxx series RTX but it still doesn't:
> 


What is the NVIDIA driver and CUDA version?

**Comment by razvanab** [comment]
Driver version: 581.29
Cuda version: cuda_13.0.r13.0

**Comment by fszontagh** [comment]
Yeah, something weird happening here. Your 3050 is sm_86 which is built with the workflow. You driver is too new and the binary is built with CUDA12, but in theory the CUDA 13 is backward compatible. 

Maybe can you try to run the linux binary in WSL?

**Comment by razvanab** [comment]
I ended up building an exe from the source and now I test it. Should I post the link to the build here or something if it ends up working?

**Comment by razvanab** [comment]
It did work by building the bins but is very slow using chroma. Around  220s/it
On comfy I get under 30s/it sometimes even less.

This is the command I use. Maybe I did something wrong:

.\sd.exe --diffusion-model "D:\MODELS\Chroma\Chroma1-HD-Flash-Q8_0.gguf" --t5xxl "D:\MODELS\Clip\flan_t5_xxl_TE-only_Q6_K.gguf" --vae "D:\MODELS\Vae\Vae_FLUX.1-schnell.safetensors" --prompt "a woman face" --clip-on-cpu  --vae-tiling --steps 9 --guidance 1 --chroma-disable-dit-mask

**Comment by fszontagh** [comment]
> I ended up building an exe from the source and now I test it. Should I post the link to the build here or something if it ends up working?

May you can run this on the dlls?
`cuobjdump --list-elf stable-diffusion.dll`

Once for the prebuild binary, once on your binary to see the difference. This will show which cuda kernel built into the dll.

**Comment by razvanab** [comment]
Ok, this is interesting.

[new_bin.txt](https://github.com/user-attachments/files/22323506/new_bin.txt)
[old_bin.txt](https://github.com/user-attachments/files/22323507/old_bin.txt)

**Comment by fszontagh** [comment]
> Ok, this is interesting.
> 
> [new_bin.txt](https://github.com/user-attachments/files/22323506/new_bin.txt) [old_bin.txt](https://github.com/user-attachments/files/22323507/old_bin.txt)

At the 'old', run the command on the dll.

This is mine on linux (built locally with native arch.):

```
cuobjdump --list-elf libstable-diffusion_cuda.so 
ELF file    1: tmpxft_000515aa_00000000-0.sm_86.cubin
ELF file    2: tmpxft_000515aa_00000000-1.sm_86.cubin
ELF file    3: tmpxft_000515aa_00000000-2.sm_86.cubin
ELF file    4: tmpxft_000515aa_00000000-3.sm_86.cubin
ELF file    5: tmpxft_000515aa_00000000-4.sm_86.cubin
ELF file    6: tmpxft_000515aa_00000000-5.sm_86.cubin
ELF file    7: tmpxft_000515aa_00000000-6.sm_86.cubin
ELF file    8: tmpxft_000515aa_00000000-7.sm_86.cubin
ELF file    9: tmpxft_000515aa_00000000-8.sm_86.cubin
ELF file   10: tmpxft_000515aa_00000000-9.sm_86.cubin
ELF file   11: tmpxft_000515aa_00000000-10.sm_86.cubin
ELF file   12: tmpxft_000515aa_00000000-11.sm_86.cubin
ELF file   13: tmpxft_000515aa_00000000-12.sm_86.cubin
ELF file   14: tmpxft_000515aa_00000000-13.sm_86.cubin
ELF file   15: tmpxft_000515aa_00000000-14.sm_86.cubin
ELF file   16: tmpxft_000515aa_00000000-15.sm_86.cubin
ELF file   17: tmpxft_000515aa_00000000-16.sm_86.cubin
ELF file   18: tmpxft_000515aa_00000000-17.sm_86.cubin
ELF file   19: tmpxft_000515aa_00000000-18.sm_86.cubin
ELF file   20: tmpxft_000515aa_00000000-19.sm_86.cubin
ELF file   21: tmpxft_000515aa_00000000-20.sm_86.cubin
ELF file   22: tmpxft_000515aa_00000000-21.sm_86.cubin
ELF file   23: tmpxft_000515aa_00000000-22.sm_86.cubin
ELF file   24: tmpxft_000515aa_00000000-23.sm_86.cubin
ELF file   25: tmpxft_000515aa_00000000-24.sm_86.cubin
ELF file   26: tmpxft_000515aa_00000000-25.sm_86.cubin
ELF file   27: tmpxft_000515aa_00000000-26.sm_86.cubin
ELF file   28: tmpxft_000515aa_00000000-27.sm_86.cubin
ELF file   29: tmpxft_000515aa_00000000-28.sm_86.cubin
ELF file   30: tmpxft_000515aa_00000000-29.sm_86.cubin
ELF file   31: tmpxft_000515aa_00000000-30.sm_86.cubin
ELF file   32: tmpxft_000515aa_00000000-31.sm_86.cubin
ELF file   33: tmpxft_000515aa_00000000-32.sm_86.cubin
ELF file   34: tmpxft_000515aa_00000000-33.sm_86.cubin
ELF file   35: tmpxft_000515aa_00000000-34.sm_86.cubin
ELF file   36: tmpxft_000515aa_00000000-35.sm_86.cubin
ELF file   37: tmpxft_000515aa_00000000-36.sm_86.cubin
ELF file   38: tmpxft_000515aa_00000000-37.sm_86.cubin
ELF file   39: tmpxft_000515aa_00000000-38.sm_86.cubin
ELF file   40: tmpxft_000515aa_00000000-39.sm_86.cubin
ELF file   41: tmpxft_000515aa_00000000-40.sm_86.cubin
ELF file   42: tmpxft_000515aa_00000000-41.sm_86.cubin
ELF file   43: tmpxft_000515aa_00000000-42.sm_86.cubin
ELF file   44: tmpxft_000515aa_00000000-43.sm_86.cubin
ELF file   45: tmpxft_000515aa_00000000-44.sm_86.cubin
ELF file   46: tmpxft_000515aa_00000000-45.sm_86.cubin
ELF file   47: tmpxft_000515aa_00000000-46.sm_86.cubin
ELF file   48: tmpxft_000515aa_00000000-47.sm_86.cubin
ELF file   49: tmpxft_000515aa_00000000-48.sm_86.cubin
ELF file   50: tmpxft_000515aa_00000000-49.sm_86.cubin
ELF file   51: tmpxft_000515aa_00000000-50.sm_86.cubin
ELF file   52: tmpxft_000515aa_00000000-51.sm_86.cubin
ELF file   53: tmpxft_000515aa_00000000-52.sm_86.cubin
ELF file   54: tmpxft_000515aa_00000000-53.sm_86.cubin
ELF file   55: tmpxft_000515aa_00000000-54.sm_86.cubin
ELF file   56: tmpxft_000515aa_00000000-55.sm_86.cubin
ELF file   57: tmpxft_000515aa_00000000-56.sm_86.cubin
ELF file   58: tmpxft_000515aa_00000000-57.sm_86.cubin
ELF file   59: tmpxft_000515aa_00000000-58.sm_86.cubin
ELF file   60: tmpxft_000515aa_00000000-59.sm_86.cubin
ELF file   61: tmpxft_000515aa_00000000-60.sm_86.cubin
ELF file   62: tmpxft_000515aa_00000000-61.sm_86.cubin
ELF file   63: tmpxft_000515aa_00000000-62.sm_86.cubin
ELF file   64: tmpxft_000515aa_00000000-63.sm_86.cubin
ELF file   65: tmpxft_000515aa_00000000-64.sm_86.cubin
ELF file   66: tmpxft_000515aa_00000000-65.sm_86.cubin
ELF file   67: tmpxft_000515aa_00000000-66.sm_86.cubin
ELF file   68: tmpxft_000515aa_00000000-67.sm_86.cubin
ELF file   69: tmpxft_000515aa_00000000-68.sm_86.cubin
ELF file   70: tmpxft_000515aa_00000000-69.sm_86.cubin
ELF file   71: tmpxft_000515aa_00000000-70.sm_86.cubin
ELF file   72: tmpxft_000515aa_00000000-71.sm_86.cubin
ELF file   73: tmpxft_000515aa_00000000-72.sm_86.cubin
ELF file   74: tmpxft_000515aa_00000000-73.sm_86.cubin
ELF file   75: tmpxft_000515aa_00000000-74.sm_86.cubin
ELF file   76: tmpxft_000515aa_00000000-75.sm_86.cubin
ELF file   77: tmpxft_000515aa_00000000-76.sm_86.cubin
ELF file   78: tmpxft_000515aa_00000000-77.sm_86.cubin
ELF file   79: tmpxft_000515aa_00000000-78.sm_86.cubin
ELF file   80: tmpxft_000515aa_00000000-79.sm_86.cubin
ELF file   81: tmpxft_000515aa_00000000-80.sm_86.cubin
ELF file   82: tmpxft_000515aa_00000000-81.sm_86.cubin
ELF file   83: tmpxft_000515aa_00000000-82.sm_86.cubin
ELF file   84: tmpxft_000515aa_00000000-83.sm_86.cubin
ELF file   85: tmpxft_000515aa_00000000-84.sm_86.cubin
ELF file   86: tmpxft_000515aa_00000000-85.sm_86.cubin
ELF file   87: tmpxft_000515aa_00000000-86.sm_86.cubin
ELF file   88: tmpxft_000515aa_00000000-87.sm_86.cubin
ELF file   89: tmpxft_000515aa_00000000-88.sm_86.cubin
ELF file   90: tmpxft_000515aa_00000000-89.sm_86.cubin
ELF file   91: tmpxft_000515aa_00000000-90.sm_86.cubin
ELF file   92: tmpxft_000515aa_00000000-91.sm_86.cubin
ELF file   93: tmpxft_000515aa_00000000-92.sm_86.cubin
ELF file   94: tmpxft_000515aa_00000000-93.sm_86.cubin
ELF file   95: tmpxft_000515aa_00000000-94.sm_86.cubin
ELF file   96: tmpxft_000515aa_00000000-95.sm_86.cubin
ELF file   97: tmpxft_000515aa_00000000-96.sm_86.cubin
ELF file   98: tmpxft_000515aa_00000000-97.sm_86.cubin
ELF file   99: tmpxft_000515aa_00000000-98.sm_86.cubin
ELF file  100: tmpxft_000515aa_00000000-99.sm_86.cubin
```

**Comment by razvanab** [comment]
Oh, on the dll. Sorry. But when I build it, it didn't generate a dll, just the exe.

[dll.txt](https://github.com/user-attachments/files/22323530/dll.txt)

**Comment by wbruna** [comment]
> It did work by building the bins but is very slow using chroma. Around 220s/it
> On comfy I get under 30s/it sometimes even less.

I don't know if Comfy has tricks to make it fast, but that GGUF is rather big for your card:

> GPU: RTX 3050 8GB Vram

> memory size = 12856.43MB (VRAM 9130.21MB, RAM 3726.22MB): text_encoders 3726.22MB(RAM), diffusion_model 9035.64MB(VRAM), vae 94.57MB(VRAM), controlnet 0.00MB(VRAM), pmid 0.00MB(RAM)

**Comment by razvanab** [comment]
I know that but strangely it works well in comfy. I will try with a smaller quantization.  Oh, and it works great in SDXL with the bins I build. Under 2it/s. Thank you for your time.

**Comment by razvanab** [comment]
Bins for RTX 3xxx series. Please scan it with a bajillion antiviruses first. I am a beginner at all this compiler stuff.

https://drive.google.com/file/d/1ZzYQ1Rybd-1B6ChvVfQXelztjDphR5YU/view?usp=drive_link

**Comment by fszontagh** [comment]
> I know that but strangely it works well in comfy. I will try with a smaller quantization. Oh, and it works great in SDXL with the bins I build. Under 2it/s. Thank you for your time.

Maybe you can try the --vae-on-cpu flag too:

`.\sd.exe --diffusion-model "D:\MODELS\Chroma\Chroma1-HD-Flash-Q8_0.gguf" --t5xxl "D:\MODELS\Clip\flan_t5_xxl_TE-only_Q6_K.gguf" --vae "D:\MODELS\Vae\Vae_FLUX.1-schnell.safetensors" --prompt "a woman face" --clip-on-cpu --vae-on-cpu --vae-tiling --steps 9 --guidance 1 --chroma-disable-dit-mask `

This may be slower generation at the end.

**Comment by razvanab** [comment]
I did try with that too. Still taking a lot of time. I am curious actually what Comfy does to make it work faster.
